### ISSUE TITLE
speed issue when audio files are long

### ISSUE THREAD

**Issue by keunwoochoi** [hipstas/kaldi-pop-up-archive#4]
Hi, thanks a lot for this awesome repo. As a background - I'm experienced in audio tasks in general but not really in ASR. 
After installing everything, I tried to test it with a long mp3 file (like, 2hrs) to realize it takes almost forever. When the file is short (3 minutes), I quickly could get the results. But there was an issue saying "I'm splitting it to too many pieces" because I once changed some of the parameters similarly as said in README. I changed back to the original values then it worked fine. 

```bash
=================== Preparing data ==================
steps/make_mfcc.sh --nj 20 --cmd run.pl --mfcc-config exp/mfcc.conf /var/extra/audio/work/audio-tmp-reactive-teaser-v3_16kHz-4218/dataPrep exp/make_mfcc/test /var/extra/audio/work/audio-tmp-reactive-teaser-v3_16kHz-4218/mfcc
utils/validate_data_dir.sh: Successfully validated data-directory /var/extra/audio/work/audio-tmp-reactive-teaser-v3_16kHz-4218/dataPrep
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
You are splitting into too many pieces! [reduce $nj] at utils/split_scp.pl line 209, <I> line 10.
steps/compute_cmvn_stats.sh /var/extra/audio/work/audio-tmp-reactive-teaser-v3_16kHz-4218/dataPrep exp/make_mfcc/test /var/extra/audio/work/audio-tmp-reactive-teaser-v3_16kHz-4218/mfcc
make_cmvn.sh: no such file /var/extra/audio/work/audio-tmp-reactive-teaser-v3_16kHz-4218/dataPrep/feats.scp
```

So, here's the question - I think I need to know something about the length of the audio files, or some related parameters, like, how to make an audio file into many occurrences for example. The situation is, there could be short (~10 mins) to long (2-3 hours) audio files. How should I deal with it? What'd be the right keywords to google?

**Comment by stevemclaugh** [comment]
I'm not sure if long audio files take disproportionately longer to complete or not. I expect each audio file to take around 5x its original duration, but it does seem like a few take much longer. They do all finish eventually.

I put this Docker image together using [this repo](https://github.com/hipstas/american-archive-kaldi), which used to be maintained by a branch of the WGBH Foundation. It's a fragile and complex system, and I never fully figured out how to tweak the settings. If you're having issues with long files, you can use ffmpeg or sox to chop everything into 1-hour segments.

At this point, though, you might be better off trying [Google's speech-to-text service](https://cloud.google.com/speech-to-text/). Their transcripts are cleaner, and the price has dropped to around $1.40 per hour of audio.

**Comment by keunwoochoi** [comment]
I see, thanks for your answer. 
> $1.40/h

That sounds like a good deal.
